#!/bin/bash

cat << EOF >> /etc/dd-agent/supervisor.conf

[program:dogwatcher-dns]
command=/usr/libexec/dogwatcher-dns.pl
stdout_logfile=NONE
stderr_logfile=NONE
redirect_stderr=true
priority=999
startsecs=3
startretries=1000000
user=named
EOF
