#!/bin/bash

LOGGER_BIN='/usr/bin/logger'
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/root/bin

# Set up the logger command if the binary is installed
if [ ! -x $LOGGER_BIN ]; then
    echo "ERROR: 'logger' binary not found - Aborting"
    echo "ERROR: '$BASH_SOURCE' Line: '$LINENO'"
    exit 2
else
    LOGGER="$LOGGER_BIN --stderr --priority local7.info --tag dns-server-boot"
fi

# Exit on any error
set -e

# Generate rndc key
if [[ ! -f /var/named/chroot/etc/rndc.key ]]; then
   rm -f /var/named/chroot/etc/rndc.key
   /usr/sbin/rndc-confgen -r /dev/urandom -a -k rndckey -b 384 -c /var/named/chroot/etc/rndc.key
   chown root:named /var/named/chroot/etc/rndc.key
   chmod 0640 /var/named/chroot/etc/rndc.key
fi

# Load DNS data
if [[ ! -d /var/named/chroot/var/named/.svn ]]; then
   sudo -u named-update /usr/sbin/dns-server-init
else
   sudo -u named-update /usr/bin/namedctl update | $LOGGER
fi

# (Re)start named
service named restart 2>&1 | $LOGGER

# Run a service test
namedctl test | $LOGGER

# Associate our EIP
/usr/sbin/dns-server-associate-eip
