#!/bin/bash

eval $(curl -s -fq http://169.254.169.254/latest/user-data)
region=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed -e 's/[a-z]$//g')
instance_id=$(curl -s -fq http://169.254.169.254/latest/meta-data/instance-id)

# Look up our EIP ID
eip_id=$(aws --region $region cloudformation describe-stacks --stack-name $NUBIS_STACK | jq --raw-output '.Stacks[].Outputs[] | select(.OutputKey=="ElasticIP") | .OutputValue')

# Check to see if our EIP is already associated
if [[ "$eip_id" ]]; then
   association_id=$(aws --region $region ec2 describe-addresses --allocation-ids "$eip_id" | jq '.Addresses[] | select(.AssociationId != null) | .AssociationId')

   # If the association_id is empty, then associate the EIP
   if [[ -z "$association_id" ]]; then
      aws --region $region ec2 associate-address --instance-id $instance_id --allocation-id $eip_id
   fi
fi
