#!/bin/bash

LOGGER_BIN='/usr/bin/logger'
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/root/bin

# Set up the logger command if the binary is installed
if [ ! -x $LOGGER_BIN ]; then
    echo "ERROR: 'logger' binary not found - Aborting"
    echo "ERROR: '$BASH_SOURCE' Line: '$LINENO'"
    exit 2
else
    LOGGER="$LOGGER_BIN --stderr --priority local7.info --tag dns-server-boot"
fi

# Generate rndc key
if [[ ! -f /var/named/chroot/etc/rndc.key ]]; then
   rm -f /var/named/chroot/etc/rndc.key
   /usr/sbin/rndc-confgen -r /dev/urandom -a -k rndckey -b 384 -c /var/named/chroot/etc/rndc.key
   chown root:named /var/named/chroot/etc/rndc.key
   chmod 0640 /var/named/chroot/etc/rndc.key
fi

# Initialize our instance-specific configuration options
local_address=$(curl -sS --fail http://169.254.169.254/latest/meta-data/local-ipv4)
echo "listen-on { ${local_address}; };" > /var/named/chroot/etc/named-options.conf
echo "listen-on-v6 {none;};" >> /var/named/chroot/etc/named-options.conf
echo 'pid-file "/run/named/named.pid";' >> /var/named/chroot/etc/named-options.conf

# Load DNS data
if [[ ! -d /var/named/chroot/var/named/.svn ]]; then
   sudo -u named-update /usr/sbin/dns-server-init
else
   sudo -u named-update /usr/bin/namedctl update | $LOGGER
fi

# (Re)start named
service named-chroot restart 2>&1 | $LOGGER

# Run a service test
output=$(namedctl test)
namedctl_test=$?

# Dump log contents to amazon system log, if the test failed.
if [[ $namedctl_test -ne 0 ]]; then
   tail -n 50 /var/log/messages
fi

# Log output of test for syslog
echo "$output" | $LOGGER

# Associate our EIP if the test was successful.
if [[ $namedctl_test -eq 0 ]]; then
   /usr/sbin/dns-server-associate-eip
fi

# Start collecting metrics for datadog
sudo -u named /usr/libexec/dogwatcher-dns &
